import Head from 'next/head';
import { Category, Product } from '@/models/Types';
import { getAllProducts, getProductByCategoryId } from '@/services/api/product';
import ProductsSlider from '@/components/Home/ProductsSlider';
import Banner from '@/components/Home/Banner';
import Comments from '../components/Home/Comments';
import CategorisSlider from '@/components/Home/CategorisSlider';
import { getAllCategories } from '@/services/api/category';
 


interface IProps {
    productsForHero: Product[]
    fantsyProduct: Product[]
    horrorProduct: Product[]
    allProducts:Product[]
    categories:Category[]
}

export default function HomePage({ fantsyProduct,allProducts ,categories}: IProps) {

    if(allProducts === undefined){
        return <div>loading</div>
    }
    return (
        <>
            <Head>
                <title>خانه</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Images/logo2.png" />
            </Head>

            <div >
                <Banner/>
            </div>

           <main className="w-full px-4 sm:px-8 lg:px-4 2xl:px-32 mt-44">
            <ProductsSlider products={allProducts} title={'جدیدترین کتاب ها '}/>
            <ProductsSlider products={fantsyProduct} title={'فانتزی'}/>
            <Comments/>
            <CategorisSlider categories={categories}/>
           </main>

        </>
    )
}


export const getStaticProps = async () => {

    const fantsyProduct = await getProductByCategoryId('64dd173b0e366d6edaece779', 20,1);
    const horrorProduct = await getProductByCategoryId('64defdace7d0b3b42651f804', 20,1);
    const allProducts = await getAllProducts(10)
    const categories = await getAllCategories();
    return {
        props: {
            allProducts:allProducts,
            fantsyProduct:fantsyProduct.products.reverse(),
            categories:categories,
            NotFound:true
        },
        revalidate:18,
        
    }
}