import Head from 'next/head';

export default function HomePage() {
    return (
        <>
            <Head>
                <title>خانه</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Images/logo2.png" />
            </Head>

            <div className=''>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p><p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>

               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>

               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>

               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>

               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p>

               <p> Lorem ipsum dolor sit amet.</p>
               <p> Lorem ipsum dolor sit amet.</p><p> Lorem ipsum dolor sit amet.</p>

            </div>
        </>
    )
}
