import Head from 'next/head';
import Hero from '../../components/Home/Hero';

import { Product } from '@/models/Types';
import { getAllProducts } from '@/services/api/product';


interface IProps {
    productsForHero: Product[]
}

export default function HomePage({ productsForHero }: IProps) {
    return (
        <>
            <Head>
                <title>خانه</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/Images/logo2.png" />
            </Head>

            <div className='p-'>
                <Hero products={productsForHero} />
            </div>
        </>
    )
}


export const getStaticProps = async () => {
    let response =await getAllProducts();
    response = await response.reverse().slice(0,7);

    return {
        props: {
            productsForHero: response,
        },
    }
}